name: iris
version: 2.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  dio: ^5.0.2
  logger: ^1.0.0
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3
  flutter_native_splash: ^2.0.5
  permission_handler: ^9.2.0
  web_socket_channel: ^2.0.0
  geolocator: ^9.0.0
  flutter_zoom_drawer: ^0.5.2
  sizer: ^2.0.15
  intl: ^0.17.0
  lottie: ^2.2.0
  store_launcher_plus: ^2.0.2
  flutter_polyline_points: ^1.0.0
  xml: ^5.3.1
  battery_optimizer: ^1.0.1
  flutter_expandable_fab: ^3.0.3
  gifx: ^1.0.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  collection: ^1.15.0
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

