name: IRIS Audit Calculator

on:
  push:
    branches: ["main"]
    paths:
      - 'moteur/**' # Ne se lance que si les scripts de calcul changent
  workflow_dispatch:

concurrency:
  group: "iris-audit"
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Audit
        run: |
          python moteur/calcul_stats.py
          
      - name: Save Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Calcul Audit auto [skip ci]" || exit 0
          git push
