name: Test Moteur IRIS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lancer la mise à jour
        run: |
          python moteur/update_dashboard.py
      - name: Publier le résultat
        run: |
          git config --global user.name "Robot IRIS"
          git config --global user.email "iris@github.com"
          git add README.md
          git commit -m "MAJ Dashboard Journalier"
          git push
