name: Collecte des données IRIS Ligne 58

on:
  schedule:
    # S'exécute toutes les heures (Format Cron)
    - cron: '0 * * * *'
  workflow_dispatch: # Permet de lancer la collecte manuellement pour tester

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install requests  # Ajoutez ici vos autres bibliothèques nécessaires

      - name: Exécution du script de collecte
        env:
          COLLECTION_TOKEN: ${{ secrets.COLLECTION_TOKEN }}
        run: python "data_collect.py"
