name: IRIS Ligne 58 - Collecte Haute Frequence

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  collecte:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Recuperation du code
        uses: actions/checkout@v4

      - name: 2. Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Installation de Requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 4. Execution du script
        env:
          COLLECTION_TOKEN: ${{ secrets.COLLECTION_TOKEN }}
        run: python "collecte de données.py"

      - name: 5. Sauvegarde des resultats
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "IRIS: Mise à jour positions" || exit 0
          git push
