name: IRIS Ligne 58 - Collecte Haute Frequence
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  collecte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Execution
        env:
          COLLECTION_TOKEN: ${{ secrets.COLLECTION_TOKEN }}
        run: python collecte_donnees.py
      - name: Sauvegarde
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "IRIS: Mise Ã  jour positions automatique" || exit 0
          git push
